Currently working hadoop.spec, now need to fix hadoop-hdfs for DataNode installation, currently seeing this error causing by incompatible classpath beween 2.7.3 and 3.0.0
18/03/21 20:29:17 ERROR datanode.DataNode: Exception in secureMain
java.lang.NoClassDefFoundError: org/apache/hadoop/tracing/SpanReceiverHost
	at org.apache.hadoop.hdfs.server.datanode.DataNode.startDataNode(DataNode.java:1226)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.<init>(DataNode.java:456)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.makeInstance(DataNode.java:2590)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.instantiateDataNode(DataNode.java:2492)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.createDataNode(DataNode.java:2539)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.secureMain(DataNode.java:2684)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.main(DataNode.java:2708)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.tracing.SpanReceiverHost
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more